parse_failed_pages: true
input_vars:
 - name: country_code
seeder:
  file: ./seeder/seeder.rb
parsers:
  - file: ./parsers/locations.rb
    page_type: locations
  - file: ./parsers/restaurant.rb
    page_type: restaurant
  - file: ./parsers/seed.rb
    page_type: seed
exporters:
  - exporter_name: locations_cl_csv
    exporter_type: csv
    collection: locations_cl
    offset: 0
    order: desc
    fields:
      - header: "date"
        path: "date"
      - header: "lead_id"
        path: "lead_id"
      - header: "url"
        path: "url"
      - header: "restaurant_name"
        path: "restaurant_name"
      - header: "restaurant_address"
        path: "restaurant_address1"
      - header: "restaurant_post_code"
        path: "restaurant_post_code"
      - header: "restaurant_area"
        path: "restaurant_area"
      - header: "restaurant_lat"
        path: "restaurant_lat"
      - header: "restaurant_long"
        path: "restaurant_long"
      - header: "restaurant_city"
        path: "restaurant_city"
      - header: "restaurant_country"
        path: "restaurant_country"
      - header: "restaurant_delivers"
        path: "restaurant_delivers"
      - header: "phone_number"
        path: "phone_number"
      - header: "restaurant_rating"
        path: "restaurant_rating"
      - header: "restaurant_position"
        path: "restaurant_position"
      - header: "number_of_ratings"
        path: "number_of_ratings"
      - header: "main_cuisine"
        path: "main_cuisine"
      - header: "free_field"
        path: "free_field"
  - exporter_name: locations_cl_json
    exporter_type: json
    collection: locations_cl
    write_mode: pretty_array
  - exporter_name: locations_cl_json_line
    exporter_type: json
    collection: locations_cl
    write_mode: line
  - exporter_name: locations_cz_csv
    exporter_type: csv
    collection: locations_cz
    offset: 0
    order: desc
    fields:
      - header: "date"
        path: "date"
      - header: "lead_id"
        path: "lead_id"
      - header: "url"
        path: "url"
      - header: "restaurant_name"
        path: "restaurant_name"
      - header: "restaurant_address"
        path: "restaurant_address1"
      - header: "restaurant_post_code"
        path: "restaurant_post_code"
      - header: "restaurant_area"
        path: "restaurant_area"
      - header: "restaurant_lat"
        path: "restaurant_lat"
      - header: "restaurant_long"
        path: "restaurant_long"
      - header: "restaurant_city"
        path: "restaurant_city"
      - header: "restaurant_country"
        path: "restaurant_country"
      - header: "restaurant_delivers"
        path: "restaurant_delivers"
      - header: "phone_number"
        path: "phone_number"
      - header: "restaurant_rating"
        path: "restaurant_rating"
      - header: "restaurant_position"
        path: "restaurant_position"
      - header: "number_of_ratings"
        path: "number_of_ratings"
      - header: "main_cuisine"
        path: "main_cuisine"
      - header: "free_field"
        path: "free_field"
  - exporter_name: locations_cz_json
    exporter_type: json
    collection: locations_cz
    write_mode: pretty_array
  - exporter_name: locations_cz_json_line
    exporter_type: json
    collection: locations_cz
    write_mode: line
  - exporter_name: locations_ca_csv
    exporter_type: csv
    collection: locations_ca
    offset: 0
    order: desc
    fields:
      - header: "date"
        path: "date"
      - header: "lead_id"
        path: "lead_id"
      - header: "url"
        path: "url"
      - header: "restaurant_name"
        path: "restaurant_name"
      - header: "restaurant_address"
        path: "restaurant_address1"
      - header: "restaurant_post_code"
        path: "restaurant_post_code"
      - header: "restaurant_area"
        path: "restaurant_area"
      - header: "restaurant_lat"
        path: "restaurant_lat"
      - header: "restaurant_long"
        path: "restaurant_long"
      - header: "restaurant_city"
        path: "restaurant_city"
      - header: "restaurant_country"
        path: "restaurant_country"
      - header: "restaurant_delivers"
        path: "restaurant_delivers"
      - header: "phone_number"
        path: "phone_number"
      - header: "restaurant_rating"
        path: "restaurant_rating"
      - header: "restaurant_position"
        path: "restaurant_position"
      - header: "number_of_ratings"
        path: "number_of_ratings"
      - header: "main_cuisine"
        path: "main_cuisine"
      - header: "free_field"
        path: "free_field"
  - exporter_name: locations_ca_json
    exporter_type: json
    collection: locations_ca
    write_mode: pretty_array
  - exporter_name: locations_ca_json_line
    exporter_type: json
    collection: locations_ca
    write_mode: line
  - exporter_name: locations_se_csv
    exporter_type: csv
    collection: locations_se
    offset: 0
    order: desc
    fields:
      - header: "date"
        path: "date"
      - header: "lead_id"
        path: "lead_id"
      - header: "url"
        path: "url"
      - header: "restaurant_name"
        path: "restaurant_name"
      - header: "restaurant_address"
        path: "restaurant_address1"
      - header: "restaurant_post_code"
        path: "restaurant_post_code"
      - header: "restaurant_area"
        path: "restaurant_area"
      - header: "restaurant_lat"
        path: "restaurant_lat"
      - header: "restaurant_long"
        path: "restaurant_long"
      - header: "restaurant_city"
        path: "restaurant_city"
      - header: "restaurant_country"
        path: "restaurant_country"
      - header: "restaurant_delivers"
        path: "restaurant_delivers"
      - header: "phone_number"
        path: "phone_number"
      - header: "restaurant_rating"
        path: "restaurant_rating"
      - header: "restaurant_position"
        path: "restaurant_position"
      - header: "number_of_ratings"
        path: "number_of_ratings"
      - header: "main_cuisine"
        path: "main_cuisine"
      - header: "free_field"
        path: "free_field"
  - exporter_name: locations_se_json
    exporter_type: json
    collection: locations_se
    write_mode: pretty_array
  - exporter_name: locations_se_json_line
    exporter_type: json
    collection: locations_se
    write_mode: line
  - exporter_name: locations_ar_csv
    exporter_type: csv
    collection: locations_ar
    offset: 0
    order: desc
    fields:
      - header: "date"
        path: "date"
      - header: "lead_id"
        path: "lead_id"
      - header: "url"
        path: "url"
      - header: "restaurant_name"
        path: "restaurant_name"
      - header: "restaurant_address"
        path: "restaurant_address1"
      - header: "restaurant_post_code"
        path: "restaurant_post_code"
      - header: "restaurant_area"
        path: "restaurant_area"
      - header: "restaurant_lat"
        path: "restaurant_lat"
      - header: "restaurant_long"
        path: "restaurant_long"
      - header: "restaurant_city"
        path: "restaurant_city"
      - header: "restaurant_country"
        path: "restaurant_country"
      - header: "restaurant_delivers"
        path: "restaurant_delivers"
      - header: "phone_number"
        path: "phone_number"
      - header: "restaurant_rating"
        path: "restaurant_rating"
      - header: "restaurant_position"
        path: "restaurant_position"
      - header: "number_of_ratings"
        path: "number_of_ratings"
      - header: "main_cuisine"
        path: "main_cuisine"
      - header: "free_field"
        path: "free_field"
  - exporter_name: locations_ar_json
    exporter_type: json
    collection: locations_ar
    write_mode: pretty_array
  - exporter_name: locations_ar_json_line
    exporter_type: json
    collection: locations_ar
    write_mode: line
  - exporter_name: locations_at_csv
    exporter_type: csv
    collection: locations_at
    offset: 0
    order: desc
    fields:
      - header: "date"
        path: "date"
      - header: "lead_id"
        path: "lead_id"
      - header: "url"
        path: "url"
      - header: "restaurant_name"
        path: "restaurant_name"
      - header: "restaurant_address"
        path: "restaurant_address1"
      - header: "restaurant_post_code"
        path: "restaurant_post_code"
      - header: "restaurant_area"
        path: "restaurant_area"
      - header: "restaurant_lat"
        path: "restaurant_lat"
      - header: "restaurant_long"
        path: "restaurant_long"
      - header: "restaurant_city"
        path: "restaurant_city"
      - header: "restaurant_country"
        path: "restaurant_country"
      - header: "restaurant_delivers"
        path: "restaurant_delivers"
      - header: "phone_number"
        path: "phone_number"
      - header: "restaurant_rating"
        path: "restaurant_rating"
      - header: "restaurant_position"
        path: "restaurant_position"
      - header: "number_of_ratings"
        path: "number_of_ratings"
      - header: "main_cuisine"
        path: "main_cuisine"
      - header: "free_field"
        path: "free_field"
  - exporter_name: locations_at_json
    exporter_type: json
    collection: locations_at
    write_mode: pretty_array
  - exporter_name: locations_at_json_line
    exporter_type: json
    collection: locations_at
    write_mode: line
  - exporter_name: locations_fi_csv
    exporter_type: csv
    collection: locations_fi
    offset: 0
    order: desc
    fields:
      - header: "date"
        path: "date"
      - header: "lead_id"
        path: "lead_id"
      - header: "url"
        path: "url"
      - header: "restaurant_name"
        path: "restaurant_name"
      - header: "restaurant_address"
        path: "restaurant_address1"
      - header: "restaurant_post_code"
        path: "restaurant_post_code"
      - header: "restaurant_area"
        path: "restaurant_area"
      - header: "restaurant_lat"
        path: "restaurant_lat"
      - header: "restaurant_long"
        path: "restaurant_long"
      - header: "restaurant_city"
        path: "restaurant_city"
      - header: "restaurant_country"
        path: "restaurant_country"
      - header: "restaurant_delivers"
        path: "restaurant_delivers"
      - header: "phone_number"
        path: "phone_number"
      - header: "restaurant_rating"
        path: "restaurant_rating"
      - header: "restaurant_position"
        path: "restaurant_position"
      - header: "number_of_ratings"
        path: "number_of_ratings"
      - header: "main_cuisine"
        path: "main_cuisine"
      - header: "free_field"
        path: "free_field"
  - exporter_name: locations_fi_json
    exporter_type: json
    collection: locations_fi
    write_mode: pretty_array
  - exporter_name: locations_fi_json_line
    exporter_type: json
    collection: locations_fi
    write_mode: line
  - exporter_name: locations_no_csv
    exporter_type: csv
    collection: locations_no
    offset: 0
    order: desc
    fields:
      - header: "date"
        path: "date"
      - header: "lead_id"
        path: "lead_id"
      - header: "url"
        path: "url"
      - header: "restaurant_name"
        path: "restaurant_name"
      - header: "restaurant_address"
        path: "restaurant_address1"
      - header: "restaurant_post_code"
        path: "restaurant_post_code"
      - header: "restaurant_area"
        path: "restaurant_area"
      - header: "restaurant_lat"
        path: "restaurant_lat"
      - header: "restaurant_long"
        path: "restaurant_long"
      - header: "restaurant_city"
        path: "restaurant_city"
      - header: "restaurant_country"
        path: "restaurant_country"
      - header: "restaurant_delivers"
        path: "restaurant_delivers"
      - header: "phone_number"
        path: "phone_number"
      - header: "restaurant_rating"
        path: "restaurant_rating"
      - header: "restaurant_position"
        path: "restaurant_position"
      - header: "number_of_ratings"
        path: "number_of_ratings"
      - header: "main_cuisine"
        path: "main_cuisine"
      - header: "free_field"
        path: "free_field"
  - exporter_name: locations_no_json
    exporter_type: json
    collection: locations_no
    write_mode: pretty_array
  - exporter_name: locations_no_json_line
    exporter_type: json
    collection: locations_no
    write_mode: line
  - exporter_name: locations_jp_csv
    exporter_type: csv
    collection: locations_jp
    offset: 0
    order: desc
    fields:
      - header: "date"
        path: "date"
      - header: "lead_id"
        path: "lead_id"
      - header: "url"
        path: "url"
      - header: "restaurant_name"
        path: "restaurant_name"
      - header: "restaurant_address"
        path: "restaurant_address1"
      - header: "restaurant_post_code"
        path: "restaurant_post_code"
      - header: "restaurant_area"
        path: "restaurant_area"
      - header: "restaurant_lat"
        path: "restaurant_lat"
      - header: "restaurant_long"
        path: "restaurant_long"
      - header: "restaurant_city"
        path: "restaurant_city"
      - header: "restaurant_country"
        path: "restaurant_country"
      - header: "restaurant_delivers"
        path: "restaurant_delivers"
      - header: "phone_number"
        path: "phone_number"
      - header: "restaurant_rating"
        path: "restaurant_rating"
      - header: "restaurant_position"
        path: "restaurant_position"
      - header: "number_of_ratings"
        path: "number_of_ratings"
      - header: "main_cuisine"
        path: "main_cuisine"
      - header: "free_field"
        path: "free_field"
  - exporter_name: locations_jp_json
    exporter_type: json
    collection: locations_jp
    write_mode: pretty_array
  - exporter_name: locations_jp_json_line
    exporter_type: json
    collection: locations_jp
    write_mode: line

