parse_failed_pages: true
input_vars:
 - name: country_code
seeder:
  file: ./seeder/seeder.rb
parsers:
  - file: ./parsers/locations.rb
    page_type: locations
  - file: ./parsers/restaurant.rb
    page_type: restaurant
  - file: ./parsers/seed.rb
    page_type: seed
    # disabled: true
finisher:
  file: ./finisher/finisher.rb
  disabled: false
exporters:
  - exporter_name: locations_cl_csv
    exporter_type: csv
    collection: locations
    offset: 0
    order: desc
    fields:
      - header: "date"
        path: "date"
      - header: "lead_id"
        path: "lead_id"
      - header: "url"
        path: "url"
      - header: "restaurant_name"
        path: "restaurant_name"
      - header: "restaurant_address"
        path: "restaurant_address1"
      - header: "restaurant_post_code"
        path: "restaurant_post_code"
      - header: "restaurant_area"
        path: "restaurant_area"
      - header: "restaurant_lat"
        path: "restaurant_lat"
      - header: "restaurant_long"
        path: "restaurant_long"
      - header: "restaurant_city"
        path: "restaurant_city"
      - header: "restaurant_country"
        path: "restaurant_country"
      - header: "restaurant_delivers"
        path: "restaurant_delivers"
      - header: "phone_number"
        path: "phone_number"
      - header: "restaurant_rating"
        path: "restaurant_rating"
      - header: "restaurant_position"
        path: "restaurant_position"
      - header: "number_of_ratings"
        path: "number_of_ratings"
      - header: "main_cuisine"
        path: "main_cuisine"
      - header: "free_field"
        path: "free_field"
  - export_filename: "<name>_A1Restaurants_<d:yyyyMMdd>"
    collection: locations
    excluded_fields:
      - _id
      - _gid
      - _collection
      - _created_at
      - _job_id
      - id
      - restaurant_address2
      - restaurant_id
      - cuisine_name 
      - opening_hours 
      - restaurant_tags 
      - restaurant_delivery_zones
      - free_field
      - average_rating
      - price_category
      - promotional_text
      - total_number_of_ratings
      - delivery_time
    export_extension: json.gz
    exporter_name: locations_a1
    exporter_type: json
    limit: 
    no_subfolder: true
    no_tar: true
    offset: 
    start_on_job_done: false
    write_mode: line
  - export_filename: "<name>_A2Restaurants_<d:yyyyMMdd>"
    collection: locations
    excluded_fields:
      - _id
      - _gid
      - _collection
      - _created_at
      - _job_id
      - id
      - restaurant_id
      - restaurant_name 
      - restaurant_address 
      - restaurant_address1
      - restaurant_address2
      - restaurant_post_code
      - restaurant_area 
      - restaurant_lat 
      - restaurant_long 
      - restaurant_city 
      - restaurant_country
      - restaurant_delivers 
      - phone_number 
      - restaurant_rating 
      - restaurant_position 
      - number_of_ratings 
      - main_cuisine
      - average_rating
      - price_category
      - promotional_text
      - total_number_of_ratings
      - delivery_time
    export_extension: json.gz
    exporter_name: locations_a2
    exporter_type: json
    limit: 
    no_subfolder: true
    no_tar: true
    offset: 
    start_on_job_done: false
    write_mode: line